---
- name: Install
  apt:
    name: nginx
    state: latest

- name: Start
  service:
    name: nginx
    state: started
    enabled: true

- name: Delete default conf
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: nginx reload

- name: Configure sites
  include: site.yml
  with_items: 
    - "{{ domains }}"
...