---
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable 
    state: present

- name: Install dependencies
  apt: 
    update_cache: yes
    name: ['git', 'zsh', 'nano', 'aptitude', 'docker-ce', 'docker-ce-cli', 'containerd.io', 'python3-pip']
    state: latest

# Install docker module for python   
- pip: 
    name: docker

#- name: Install Metricbeat
#  apt:
#    deb: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.9.0-amd64.deb

#- name: Configure Metricbeat
#  copy:
#    src: templates/metricbeat.j2
#    dest: /etc/metricbeat/metricbeat.yml

#- name: Metricbeat Module
#  become: yes
#  become_user: root
#  command: metricbeat modules enable system
...